# ServiceAccount used by the secret-sync Deployment in the cert-manager namespace.
# The Workload Identity annotation ties it to the same Managed Identity that
# has Key Vault Secrets User access to the AKV.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager-secret-sa
  namespace: cert-manager
  annotations:
    azure.workload.identity/client-id: "19dcd42a-34cf-4cf2-9cf4-995d1a51abe9"
