# ServiceAccount used by the secret-sync Deployment in the cert-manager namespace.
# The Workload Identity annotation ties it to the same Managed Identity that
# has Key Vault Secrets User access to the AKV.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager-secret-sa
  namespace: cert-manager
  annotations:
    azure.workload.identity/client-id: "a3f25662-c80d-4a77-a73c-2a2595ab47b9"
