# After running `terraform apply` in infra-terraform, replace the placeholder
# below with: terraform output managed_identity_client_id
apiVersion: v1
kind: ServiceAccount
metadata:
  name: news-digest-sa
  namespace: news-digest
  annotations:
    azure.workload.identity/client-id: "db5d94ff-ad50-4fa3-a50d-6e8973b9a75b"
