apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kafka-pods
  namespace: monitoring
spec:
  selector:
    matchLabels:
      strimzi.io/cluster: my-kafka
  namespaceSelector:
    matchNames:
      - kafka
  podMetricsEndpoints:
    - path: /metrics
      port: tcp-prometheus
      interval: 30s
