apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: monitoring-akv
  namespace: monitoring
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: "19dcd42a-34cf-4cf2-9cf4-995d1a51abe9"
    keyvaultName: "kv-ddot-dev-swc-001"
    tenantId: "eae82d0e-137d-4df8-ab74-34f582042d39"
    objects: |
      array:
        - |
          objectName: grafana-admin-user
          objectType: secret
        - |
          objectName: grafana-admin-password
          objectType: secret
  secretObjects:
    - secretName: grafana-admin-secret
      type: Opaque
      data:
        - objectName: grafana-admin-user
          key: admin-user
        - objectName: grafana-admin-password
          key: admin-password
